include <../common/constants.scad>

$fa = 1;
$fs = .4;

SMALL_R = 14.5 / 2;
BIG_R = 29.5 / 2;

INSIDE_HEIGHT = 4;
LID_HEIGHT = 1;

HANDLE_HEIGHT_CURVED = 13;
HANDLE_HEIGHT_EXTRA = 2;

HANDLE_LENGTH_BIG_FACTOR = 1.6;
HANDLE_LENGTH_SMALL_FACTOR = 1.2;
HANDLE_WIDTH_BIG_FACTOR = 1;
HANDLE_WIDTH_SMALL_FACTOR = 0.5;
